[build]
  command = "npm run build"
  publish = "out"

  # Use Netlify Next.js plugin
  [[plugins]]
    package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "nextjs"
